sudo: required
dist: trusty

language: go

services:
  - docker

go:
  - 1.8

script:
  - sudo add-apt-repository ppa:masterminds/glide && sudo apt-get update
  - sudo apt-get install glide
  - glide install
  - make test
