version: build-{build}.{branch}
image: Visual Studio 2017
clone_folder: C:\gopath\src\github.com\nebtex\menshend
shallow_clone: true

environment:
  GOPATH: C:\gopath

platform:
  - x64

build: off

install:
  - go version
  - go env
  - ps: Start-FileDownload 'https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-windows-amd64.zip'
  - 7z e glide-v0.12.3-windows-amd64.zip -y
  - ps: Start-FileDownload 'https://releases.hashicorp.com/vault/0.7.0/vault_0.7.0_windows_amd64.zip'
  - 7z e vault_0.7.0_windows_amd64.zip -y
  - ps: $VaultProcess = Start-Process vault server -dev -dev-root-token-id=myroot -PassThru

on_finish:
  - ps: Stop-Process -Id $VaultProcess.Id

test_script:
  - glide install
  - go test -v  ./cmd/menshend ./pkg/apis/menshend/v1 ./pkg/config ./pkg/filters ./pkg/pfclient ./pkg/pfclient/chisel/client ./pkg/pfclient/chisel/server ./pkg/resolvers ./pkg/resolvers/cache ./pkg/strategy ./pkg/utils ./pkg/utils/test

deploy: off
