version: build-{build}.{branch}
image: Visual Studio 2017 RC
clone_folder: C:\gopath\src\github.com\nebtex\menshend
shallow_clone: true

environment:
  GOPATH: C:\gopath

platform:
  - x64

build: off

install:
  - go version
  - go env
  - ps: Start-FileDownload 'https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-windows-amd64.zip'
  - 7z e glide-v0.12.3-windows-amd64.zip -y
  - docker run -d -e 'SKIP_SETCAP=yes' -e 'VAULT_DEV_ROOT_TOKEN_ID=myroot' -e 'VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200' -p 8200:8200 vault

test_script:
  - glide install
  - go test -v -coverpkg=$(go list ./... | grep -v /vendor/)

deploy: off
